events {}

http {
  server {
    listen 8080;

    # Static files / images
    location ~ ^/(images|uploads)(/|$) {
      proxy_pass http://web:8081;
      proxy_set_header Host $host;
    }

    # API routes
    location ~ ^/(brands|categories|products|users|carts|favorites|payment)(/|$) {
      proxy_pass http://api:8091;
      proxy_set_header Host $host;
    }

    # UI
    location / {
      proxy_pass http://ui:4200;
      proxy_set_header Host $host;
    }
  }
}